# 创建Tensor

In [1]:
import torch

In [2]:
torch.__version__

'1.0.0'

In [3]:
torch.cuda.is_available()

False

In [4]:
x = torch.empty(5, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5526e-42, 0.0000e+00],
        [0.0000e+00, 9.1836e-39, 0.0000e+00]])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.7073, 0.4552, 0.8030],
        [0.6701, 0.0225, 0.8982],
        [0.8815, 0.4244, 0.4362],
        [0.0639, 0.3512, 0.0740],
        [0.6288, 0.4225, 0.4220]])

In [6]:
# 创建一个5x3的long型全0的Tensor
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
x = x.new_ones(5, 3, dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.1791, 0.8166, 0.7910],
        [0.1630, 0.0947, 0.0580],
        [0.1079, 0.7918, 0.5646],
        [0.3051, 0.5816, 0.6511],
        [0.4070, 0.7323, 0.1551]])

In [10]:
x.size()

torch.Size([5, 3])

In [11]:
x.shape

torch.Size([5, 3])

# 操作

## 算术操作

In [12]:
y = torch.rand(5, 3)
x + y

tensor([[0.8049, 1.3590, 1.6555],
        [0.8715, 0.6777, 0.2794],
        [1.0608, 1.0210, 1.2778],
        [1.0230, 1.4393, 1.1290],
        [1.4017, 1.1473, 1.1071]])

In [13]:
torch.add(x, y)

tensor([[0.8049, 1.3590, 1.6555],
        [0.8715, 0.6777, 0.2794],
        [1.0608, 1.0210, 1.2778],
        [1.0230, 1.4393, 1.1290],
        [1.4017, 1.1473, 1.1071]])

In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[0.8049, 1.3590, 1.6555],
        [0.8715, 0.6777, 0.2794],
        [1.0608, 1.0210, 1.2778],
        [1.0230, 1.4393, 1.1290],
        [1.4017, 1.1473, 1.1071]])

In [15]:
y.add_(x)

tensor([[0.8049, 1.3590, 1.6555],
        [0.8715, 0.6777, 0.2794],
        [1.0608, 1.0210, 1.2778],
        [1.0230, 1.4393, 1.1290],
        [1.4017, 1.1473, 1.1071]])

## 索引

In [16]:
y = x[0, :]
y

tensor([0.1791, 0.8166, 0.7910])

In [17]:
y += 1
y

tensor([1.1791, 1.8166, 1.7910])

In [18]:
x[0, :]

tensor([1.1791, 1.8166, 1.7910])

## 改变形状

In [19]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [20]:
x += 1
print(x)
print(y)

tensor([[2.1791, 2.8166, 2.7910],
        [1.1630, 1.0947, 1.0580],
        [1.1079, 1.7918, 1.5646],
        [1.3051, 1.5816, 1.6511],
        [1.4070, 1.7323, 1.1551]])
tensor([2.1791, 2.8166, 2.7910, 1.1630, 1.0947, 1.0580, 1.1079, 1.7918, 1.5646,
        1.3051, 1.5816, 1.6511, 1.4070, 1.7323, 1.1551])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用clone创造一个副本然后再使用view。

In [21]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[1.1791, 1.8166, 1.7910],
        [0.1630, 0.0947, 0.0580],
        [0.1079, 0.7918, 0.5646],
        [0.3051, 0.5816, 0.6511],
        [0.4070, 0.7323, 0.1551]])
tensor([2.1791, 2.8166, 2.7910, 1.1630, 1.0947, 1.0580, 1.1079, 1.7918, 1.5646,
        1.3051, 1.5816, 1.6511, 1.4070, 1.7323, 1.1551])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.7616])
1.7616139650344849


# 广播机制

In [23]:
x = torch.arange(1, 3).view(1, 2)
print(x)

y = torch.arange(1, 4).view(3, 1)
print(y)

print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


# 运算的内存开销

In [24]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [25]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [26]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)  # y += x, y.add_(x)
print(id(y) == id_before)

True


# Tensor与Numpy# NTensor与Numpy#相转换

## Tensor转Numpy: numpy

In [27]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [28]:
a += 1
print(a, b)

b += 1
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


## Numpy转Tensor: from_numpy

In [29]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [30]:
a += 1
print(a, b)

b += 1
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


torch.tensor()将Numpy数组转换为Tensor，该方法总是会进行数据拷贝，返回的Tensor和原来的数据不再共享内存

In [31]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Tensor on GPU

In [32]:
if torch.cuda.is_available():
    device = torch.device('cuda')          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to('cuda')
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))       # to()还可以同时改变数据类型

In [33]:
torch.cuda.is_available()

False