In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39],
        [1.0378e-38, 8.9082e-39, 9.6429e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5417, 0.5380, 0.8519],
        [0.5926, 0.5955, 0.2614],
        [0.8214, 0.7193, 0.0214],
        [0.5059, 0.6589, 0.7159],
        [0.8145, 0.4503, 0.6715]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4245,  0.0869, -0.2496],
        [ 0.7622, -1.5367, -0.3878],
        [ 1.2597,  1.5575,  0.3205],
        [ 0.9801,  0.4080, -0.6526],
        [-0.1926,  0.5660,  0.8507]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2834,  0.7627,  0.5972],
        [ 0.8839, -1.1700,  0.2671],
        [ 1.3939,  2.1742,  1.2830],
        [ 1.0005,  0.7147, -0.5403],
        [ 0.0814,  1.0450,  0.9985]])


In [9]:
print(torch.add(x, y))

tensor([[ 1.2834,  0.7627,  0.5972],
        [ 0.8839, -1.1700,  0.2671],
        [ 1.3939,  2.1742,  1.2830],
        [ 1.0005,  0.7147, -0.5403],
        [ 0.0814,  1.0450,  0.9985]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2834,  0.7627,  0.5972],
        [ 0.8839, -1.1700,  0.2671],
        [ 1.3939,  2.1742,  1.2830],
        [ 1.0005,  0.7147, -0.5403],
        [ 0.0814,  1.0450,  0.9985]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.2834,  0.7627,  0.5972],
        [ 0.8839, -1.1700,  0.2671],
        [ 1.3939,  2.1742,  1.2830],
        [ 1.0005,  0.7147, -0.5403],
        [ 0.0814,  1.0450,  0.9985]])


In [12]:
print(x[:, 1])

tensor([ 0.0869, -1.5367,  1.5575,  0.4080,  0.5660])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
y

tensor([-0.1478,  0.3737, -0.9161, -0.9256,  0.4766,  1.4198,  0.4475, -1.2515,
         0.1335, -0.1559,  1.1780,  1.8022, -0.2467, -0.6709, -0.6958,  1.5214])

``.item()`` 将只有一个元素的张量转换为Python数值

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2206])
-1.220615267753601


## NumPy Bridge

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


``.numpy()``将Tensor转换为NumPy Array

In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


``.from_numpy``将NumPy Array转换为Tensor

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)  # a和b共享内存地址
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
