In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data) # from_numpy() 将numpy对象转换为tensor对象
tensor2array = torch_data.numpy() # 将tensor对象转换为array对象

print(
    '\nnumpy array:    ', np_data,
    '\ntorch tensor:   ', torch_data,
    '\ntensor to array: ', tensor2array
)


numpy array:     [[0 1 2]
 [3 4 5]] 
torch tensor:    tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor to array:  [[0 1 2]
 [3 4 5]]


abs 绝对值计算

In [3]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data) # 转换为32位浮点 tensor
print(
    '\abs',
    '\nnumpy: ', np.abs(data),
    '\ntorch: ', torch.abs(tensor)
)

bs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [4]:
tensor.abs()

tensor([1., 2., 1., 2.])

sin 三角函数

In [5]:
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),
    '\ntorch: ', torch.sin(tensor) 
)


sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [6]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [7]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

mean 均值

In [8]:
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),
    '\ntorch: ', torch.mean(tensor)
)


mean 
numpy:  0.0 
torch:  tensor(0.)


matrix multiplication 矩阵点乘

In [9]:
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data) # 转换成32位浮点 tensor
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),
    '\ntorch: ', torch.mm(tensor, tensor)
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


In [10]:

# incorrect method
data = np.array(data)
tensor = torch.Tensor(data)
print(
    '\nmatrix multiplication (dot)',
    '\nnumpy: ', data.dot(data),        # [[7, 10], [15, 22]]
    '\ntorch: ', torch.dot(tensor.dot(tensor))     # NOT WORKING! Beware that torch.dot does not broadcast, only works for 1-dimensional tensor
)

RuntimeError: 1D tensors expected, got 2D, 2D tensors at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensorEvenMoreMath.cpp:723

Note that:

torch.dot(tensor1, tensor2) → float

Computes the dot product (inner product) of two tensors. Both tensors are treated as 1-D vectors.

In [11]:
tensor.mm(tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [12]:
tensor * tensor

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [13]:
torch.dot(torch.Tensor([2, 3]), torch.Tensor([2, 1]))

tensor(7.)