In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.FloatTensor([[1, 2], [3, 4]])
variable = Variable(tensor, requires_grad=True)

print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [3]:
t_out = torch.mean(tensor * tensor)
v_out = torch.mean(variable * variable)

print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [4]:
v_out.backward()

$$ v_{out} = \frac {1} {4} \times sum(variable^2) $$

the gradients w.r.t the variable,

$$ \frac {d(v_{out})} {d(variable)} = \frac {1} {4} \times 2 \times variable = \frac {variable} {2}$$

In [5]:
variable.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [6]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [7]:
variable.data  # 

tensor([[1., 2.],
        [3., 4.]])

In [8]:
variable.detach().numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [9]:
variable.data.numpy() # numpy format

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [10]:
type(v_out)

torch.Tensor

In [11]:
type(v_out.data)

torch.Tensor

In [12]:
type(variable.detach())

torch.Tensor