# 读取Tensor

In [1]:
import torch
from torch import nn

In [2]:
x = torch.ones(3)
torch.save(x, 'x.pt')

In [3]:
x2 = torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [5]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

# 读取模型
## state_dict

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)
        
    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

In [7]:
net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.0501,  0.1947, -0.1353],
                      [-0.3974, -0.2998,  0.0008]])),
             ('hidden.bias', tensor([-0.5393,  0.2817])),
             ('output.weight', tensor([[-0.1496,  0.4774]])),
             ('output.bias', tensor([-0.6197]))])

In [8]:
optimizer = torch.optim.SGD(net.parameters(),
                            lr=0.001,
                            momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [1739314374480, 1739314374552, 1739314326984, 1739314327344]}]}

## 保存和加载模型
PyTorch中保存和加载训练模型有两种常见的方法:

1. 仅保存和加载模型参数(state_dict)；
2. 保存和加载整个模型。

**1. 保存和加载state_dict(推荐方式)**

保存

`# 推荐的文件后缀名是pt或pth`

`torch.save(model.state_dict(), PATH)`

加载

`model = TheModelClass(*args, **kwargs)`
`model.load_state_dict(torch.load(PATH))`

**2. 保存和加载整个模型**

保存

`torch.save(model, PATH)`

加载

`model = torch.load(PATH)`

In [9]:
X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])