# 计算设备

In [1]:
import torch
from torch import nn

torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
torch.cuda.get_device_name(0)

'GeForce MX150'

# Tensor的GPU计算

In [5]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [6]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [7]:
x.device

device(type='cuda', index=0)

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
y = x ** 2
y

tensor([1, 4, 9], device='cuda:0')

In [11]:
# 在CPU和GPU上的数据不能直接做运算
z = y + x.cpu()

RuntimeError: expected device cuda:0 but got device cpu

# 模型的GPU计算

In [12]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [13]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [14]:
x = torch.rand(2, 3).cuda()
net(x)

tensor([[0.3215],
        [0.2627]], device='cuda:0', grad_fn=<AddmmBackward>)