In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from torch import nn
import os
import datetime
%matplotlib inline

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [2]:
n = 400 # 样本数量
X = 10 * torch.rand([n, 2]) - 5.0
w0 = torch.tensor([[2.0], [-3.0]])
b0 = torch.tensor([[10.0]])

In [3]:
X.shape

torch.Size([400, 2])

In [4]:
w0.shape

torch.Size([2, 1])

In [5]:
torch.normal(0.0, 2.0, size=[n, 1]).shape

torch.Size([400, 1])

In [6]:
Y = torch.mm(X, w0) + b0 + torch.normal(0.0, 2.0, size=[n, 1])

In [7]:
A = torch.arange(20).reshape(5, 4).float()
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [8]:
B = torch.ones(4, 3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
A.shape, B.shape

(torch.Size([5, 4]), torch.Size([4, 3]))

In [10]:
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [11]:
a = torch.rand(2, 2)
# print(a)
b = torch.rand(2, 3)
c = torch.mm(a, b)
d = torch.matmul(a, b)
e = a@b
print('c, b, e = ', c, '\n', d, '\n', e)

c, b, e =  tensor([[0.0834, 0.4315, 0.3190],
        [0.0803, 0.4091, 0.2871]]) 
 tensor([[0.0834, 0.4315, 0.3190],
        [0.0803, 0.4091, 0.2871]]) 
 tensor([[0.0834, 0.4315, 0.3190],
        [0.0803, 0.4091, 0.2871]])
