In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39],
        [1.0378e-38, 8.9082e-39, 9.6429e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2566, 0.4028, 0.5417],
        [0.5066, 0.0225, 0.5981],
        [0.6896, 0.2767, 0.4048],
        [0.9190, 0.4573, 0.9969],
        [0.6234, 0.2088, 0.6245]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.7109,  1.0565,  0.2641],
        [-0.9783,  0.5496, -1.4658],
        [ 0.7744,  0.3816,  0.8237],
        [ 0.2232,  2.1943,  0.3701],
        [-0.6622, -0.2723, -0.2736]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.0596,  1.2021,  0.6950],
        [-0.5942,  1.4121, -1.2928],
        [ 1.3038,  1.3348,  1.5387],
        [ 0.4084,  2.1958,  0.9343],
        [-0.6226,  0.5613, -0.1902]])


In [9]:
print(torch.add(x, y))

tensor([[ 2.0596,  1.2021,  0.6950],
        [-0.5942,  1.4121, -1.2928],
        [ 1.3038,  1.3348,  1.5387],
        [ 0.4084,  2.1958,  0.9343],
        [-0.6226,  0.5613, -0.1902]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.0596,  1.2021,  0.6950],
        [-0.5942,  1.4121, -1.2928],
        [ 1.3038,  1.3348,  1.5387],
        [ 0.4084,  2.1958,  0.9343],
        [-0.6226,  0.5613, -0.1902]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.0596,  1.2021,  0.6950],
        [-0.5942,  1.4121, -1.2928],
        [ 1.3038,  1.3348,  1.5387],
        [ 0.4084,  2.1958,  0.9343],
        [-0.6226,  0.5613, -0.1902]])


In [12]:
print(x[:, 1])

tensor([ 1.0565,  0.5496,  0.3816,  2.1943, -0.2723])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
y

tensor([-0.7327,  0.0074,  1.2458, -0.4313, -0.3524, -0.1555, -0.2243,  0.5558,
         0.5343,  0.6883, -0.6848,  0.3266,  0.5395,  0.9666,  0.1269,  0.2706])

``.item()`` 将只有一个元素的张量转换为Python数值

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4438])
0.4438374638557434


## NumPy Bridge

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


``.numpy()``将Tensor转换为NumPy Array

In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


``.from_numpy``将NumPy Array转换为Tensor

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)  # a和b共享内存地址
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
