## Tensor
- ``.requires_grad=True``追踪其上的所有操作
- ``.backward()``计算梯度
- ``.grad``梯度值
- ``detach()``取消追踪
- ``with torch.no_grad():``不追踪其上的操作
- ``.grad_fn``怎样建立的

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
# 怎么建立的
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
a = torch.randn(2, 2)  # 默认requires_grad=False
a = ((a * 3) / (a - 1))
print(a.requires_grad)

# requires_grad_ 原地修改，是否计算梯度
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## Gradients

In [7]:
# 计算梯度
out.backward()

打印梯度 $d(out)/dx$

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


``.data``将requires_grad=True的Tensor转换requires_grad=False的Tensor

``.norm()``范数

In [9]:
x = torch.randn(3, requires_grad=True)

y = x * 2

while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1485.4562,    -9.2208,   602.8906], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)  # 计算梯度

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


``with torch.no_grad():``不追踪梯度

In [11]:
print(x.requires_grad)
print((x ** 2).requires_grad)

# 不计算梯度
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


``.detach()``返回一个新的含有相同内容的Tensor，但是是不追踪梯度的

In [12]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
